name: elements_app
description: Browse the elements of the periodic table!

version: 1.1.0+1


environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.0"


flutter:

  uses-material-design: true

  assets:
    - assets/elementsGrid.json

  fonts:
    - family: Share Tech Mono
      fonts:
      - asset: assets/fonts/ShareTechMono-Regular.ttf
    - family: Roboto Condensed
      fonts:
      - asset: assets/fonts/RobotoCondensed-Regular.ttf
      - asset: assets/fonts/RobotoCondensed-Light.ttf
        weight: 300


flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/launcher_icons/launcher_android.png"
  image_path_ios: "assets/launcher_icons/launcher_ios.png"
  adaptive_icon_foreground: "assets/launcher_icons/launcher_adaptive_foreground.png"
  adaptive_icon_background: "assets/launcher_icons/launcher_adaptive_background.png"